export const pivotes = {
  Espalda: { x: 1550, y: 510 },
  Pecho: { x: 1024, y: 700 },
  "Manga Izq": { x: 1700, y: 1000 },
  "Manga Der": { x: 340, y: 1000 },
};

export const texturasDisponibles = [
  "./pattern1.svg",
  "./pattern2.svg",
  "./pattern3.svg",
  "./pattern4.svg",
  "./pattern5.svg",
];

export const modelosTorsoDisponibles = {
  "Torso A": "./ModeloMasc.glb",
  "Torso B": "./ModeloFem.glb",
};

export const paletasDisponibles = [
  {
    id: "sunset-pop",
    nombre: "Sunset Pop",
    principal: "#f32a4f",
    secundario: "#f49846",
    terciario: "#feca3c",
  },
  {
    id: "mint-fresh",
    nombre: "Mint Fresh",
    principal: "#4fb270",
    secundario: "#bdd24c",
    terciario: "#ffffff",
  },
  {
    id: "pink-breeze",
    nombre: "Pink Breeze",
    principal: "#e8528b",
    secundario: "#92d3e9",
    terciario: "#ffffff",
  },
  {
    id: "berry-flare",
    nombre: "Berry Flare",
    principal: "#d12e4f",
    secundario: "#ffdd57",
    terciario: "#ffdd57",
  },
  {
    id: "green-harvest",
    nombre: "Green Harvest",
    principal: "#33ab58",
    secundario: "#4fb270",
    terciario: "#ffcb24",
  },
  {
    id: "sunburst-gold",
    nombre: "Sunburst Gold",
    principal: "#f49846",
    secundario: "#feca3c",
    terciario: "#f9dc62",
  },
  {
    id: "violet-pulse",
    nombre: "Violet Pulse",
    principal: "#b26fb1",
    secundario: "#6f3893",
    terciario: "#ffffff",
  },
  {
    id: "deep-ocean",
    nombre: "Deep Ocean",
    principal: "#006bb7",
    secundario: "#343390",
    terciario: "#f9dc62",
  },
  {
    id: "crimson-night",
    nombre: "Crimson Night",
    principal: "#f32a4f",
    secundario: "#343390",
    terciario: "#f9dc62",
  },
  {
    id: "ocean-light",
    nombre: "Ocean Light",
    principal: "#006bb7",
    secundario: "#92d3e9",
    terciario: "#ffffff",
  },
  {
    id: "violet-storm",
    nombre: "Violet Storm",
    principal: "#6f3893",
    secundario: "#b26fb1",
    terciario: "#ffffff",
  },
  {
    id: "sunfire-kit",
    nombre: "Sunfire Kit",
    principal: "#f49846",
    secundario: "#f32a4f",
    terciario: "#ffffff",
  },
  {
    id: "night-playmaker",
    nombre: "Night Playmaker",
    principal: "#343390",
    secundario: "#f32a4f",
    terciario: "#ffffff",
  },
  {
    id: "rose-legend",
    nombre: "Rose Legend",
    principal: "#e8528b",
    secundario: "#ffffff",
    terciario: "#343390",
  },
  {
    id: "black-toon",
    nombre: "Rose Legend",
    principal: "#0d0d0d",
    secundario: "#454545",
    terciario: "#ffffff",
  },
];

export const fuenteTextoPredeterminada = "Anton";
export const anchoMaximoNombreEspalda = 650;
export const maxCaracteresNumero = 2;
export const inclinacionPlayeraCuello = (5 * Math.PI) / 180;

export const limitarNumero = (numero) =>
  String(numero).slice(0, maxCaracteresNumero);

export function createInitialSettings() {
  return {
    nombre: "JUGADOR",
    numero: "10",
    modeloTorso: modelosTorsoDisponibles["Torso A"],
    fuente: fuenteTextoPredeterminada,
    negrita: false,
    tamanioNombre: 175,
    tamanioNumero: 355,
    posicionPredefinida: "Espalda",
    posX: 1550,
    posY: 510,
    espaciado: 280,
    escalaX: 1,
    escalaY: 1,
    pechoX: 750,
    pechoY: 1450,
    pechoEscala: 0.5,
    mangaDerX: 490,
    mangaDerY: 1930,
    mangaDerEscala: 0.4,
    colorTexto: paletasDisponibles[0].terciario,
    texturaBase: texturasDisponibles[0],
    paletaColor: paletasDisponibles[0].id,
    colorBloqueA: paletasDisponibles[0].principal,
    colorBloqueB: paletasDisponibles[0].secundario,
    colorBloqueC: paletasDisponibles[0].terciario,
    modoPivotes: "espalda",
    mostrarBloques: true,
    mostrarLogos: true,
    // Logos del pattern
    logo1_x: 555,
    logo1_y: 686,
    logo1_esc: 1.72,
    logo1_rot: 0,
    logo2_x: 555,
    logo2_y: 686,
    logo2_esc: 1.72,
    logo2_rot: 0,
    logo3_x: 555,
    logo3_y: 686,
    logo3_esc: 1.72,
    logo3_rot: 0,
    logo4_x: 700,
    logo4_y: 630,
    logo4_esc: 0.8,
    logo4_rot: 0,
    logo5_x: 700,
    logo5_y: 630,
    logo5_esc: 0.8,
    logo5_rot: 0,
    // Iluminacion
    intensidadLuzAmbiente: 3.65,
    intensidadLuzPrincipal: 10,
    colorLuzAmbiente: "#ffffff",
    colorLuzPrincipal: "#fff4dd",
    posicionLuzX: -0.08,
    posicionLuzY: 0.42,
    posicionLuzZ: -0.82,
    distanciaLuz: 1.8,
    anguloLuz: 1.48,
    penumbraLuz: 1.0,
    decayLuz: 1.0,
    // Fondo y escena
    usarImagenFondo: true,
    imagenFondoPath: "./FONDOPLAYERA.png",
    colorFondo: "#101010",
    colorFondo2: "#2e4366",
    logoPasaHorizontalX: -0.65,
    logoPasaHorizontalY: 0.6,
    logoPasaHorizontalEscala: 0.5,
    logoPasaVerticalX: 0,
    logoPasaVerticalY: 0.8,
    logoPasaVerticalEscala: 1,
    // HDRI y material
    usarHDRI: true,
    intensidadHDRI: 0.35,
    exposure: 0.25,
    roughness: 0.8,
    metalness: 0.4,
    outlineActivo: false,
    outlineColor: "#ffffff",
    outlineGrosor: 0.005,
    outlineIrregularidad: 9,
    outlineEscalaRuido: 0.5,
    outlineUmbralSilueta: 0,
    outlineSuavidadSilueta: 0.01,
    outlineReducirAbajo: 1,
    outlineSuavidadAbajo: 0.01,
    siluetaExteriorActiva: true,
    siluetaExteriorColor: "#ffffff",
    siluetaExteriorGrosor: 8,
    siluetaExteriorOpacidad: 0.8,
    siluetaExteriorIrregularidad: 0,
    // Coreografia de video
    videoDuracionMs: 5000,
    videoModeloProporcionPantalla: 0,
    videoGiroInicioMs: 200,
    videoGiroDuracionMs: 2200,
    videoGiroGrados: 360,
    videoGiroEje: "y",
    videoOverlayInicioMs: 1200,
    videoOverlayFadeMs: 500,
    videoLogoX: 0,
    videoLogoY: 0.65,
    videoLogoEscalaInicio: 0.25,
    videoLogoEscalaFinal: 0.6,
    videoLogoEscalaFinalVertical: 2,
    videoHashtag: " #PASAELBALÓN ",
    videoHashtagX: 0,
    videoHashtagY: -0.7,
    videoHashtagEscala: 0.5,
    videoHashtagEscalaVertical: 1,
    videoDesactivarHDRI: false,
    videoReflectoresActivos: false,
    videoReflectoresInicioMs: 200,
    videoReflectoresFadeMs: 700,
    videoReflectorIntensidad: 9,
    videoReflectorColor: "#fff4dd",
  };
}
